### ISSUE TITLE
Data creation and training

### ISSUE THREAD

**Issue by 44aayush** [manhdung20112000/speech-enhancement#3]
Hi Manhdung20112000,
The work you have done is awesome. I would like to know about, 
1. How have you preprocessed the dataset (what vbelz has done?)?
2. What if I wanted to add more noise to the dataset, how can it be achieved?

**Comment by manhdung20112000** [comment]
First of all, thank you for raise your issue, I really appreciate it. ✌

**1. The process of preprocessing dataset was simple:**
- _**The clean voice**_: At the moment we were making this project, we also took part in a speech processing course and all the Vietnamese article reader (clean voice) are collected inside the course.
- **_The noise_**: As I mentioned (in README), I were using the ESC-50 dataset (Dataset for Environmental Sound Classification)

After collected all the necessary audio, I mixed the clean voice and environmental noise, which has been blended with a randomization of the noise level (between 20% and 80%), together. Each mixed audio I made was truncated to approximately 1s duration. 
From here, I transformed the mixed audios into 128x128 (2D numpy) mel spectrogram image through `librosa`. Vbelz provided a great source code for done this process easily (although he seems not to support it anymore and some his `librosa functions` are out of date 😢)

**2. You can add many noise as you want**
Clone Vbelz source code to preprocessing your data and by adding it (the noise audio) into `noise` dir you can start produce your dataset. (Vbelz has a detail tutorial of how to use his code, so make sure to check it out
[Vbelz/Speech-enhancement](https://github.com/vbelz/Speech-enhancement/#prepare-the-data)

I would recommend that the more noice or voice you have, the higher number of sample should be. (In my case, I only focused on 20 noise class then only 6000 samples were created)
One more thing, when you using Vbelz code to preprocessing, because librosa is no longer support librosa.output after version 0.8.0, therefore, you should consider to replacing `librosa.output` with `soundfile.write` in [here](https://github.com/vbelz/Speech-enhancement/blob/master/prepare_data.py#L44)

**Comment by 44aayush** [comment]
I'm currently learning ML and doing a project on Denoising and Enhancement for a hands-on approach.  I see that you have a train and test function in the train.py file, so I'm assuming that you have already trained and tested the model and then deployed it on Streamlit. Therefore, if I want to train and check how it is getting trained, what command should I run for the same?

I tried python train.py => ImportError: cannot import name 'CLASSES' from 'model.config' (C:\Users\Aayush\Desktop\speech-enhancement\model\config.py)

**Comment by manhdung20112000** [comment]
**I have updated new version, check it out.**

**To recreate my experiment, you can run:**
```
python train.py 
```
with specifying run name, model, dropout rate ...
```
python train.py [-h] [--run RUN] [--model MODEL] [--dropout DROPOUT] [--epoch EPOCH] [--startfm STARTFM] [--batchsize BATCHSIZE] [--lr LR] [--tuning]

optional arguments:
  -h, --help            show this help message and exit
  --run RUN             run name
  --model MODEL         initial weights path
  --dropout DROPOUT     declear dropout rate
  --epoch EPOCH         number of epoch
  --startfm STARTFM     architecture start frame
  --batchsize BATCHSIZE
                        total batch size for all GPUs (default:
  --lr LR               learning rate (default: 0.0001)
  --tuning              no plot image for tuning
```

**Comment by 44aayush** [comment]
Thanks for your help, I will open the channel if I have any more questions 👍🏻
