### ISSUE TITLE
app_utils.py

### ISSUE THREAD

**Issue by sauravpd29** [manhdung20112000/speech-enhancement#4]
Hi  @manhdung20112000 ,
Awesome work done by you.
I wanted to know somethings related to app.
In your app_utils.py line [202] its  ` model = UNet(start_fm=32).to(device)`  where UNet class is defined in model.py.
Can the model  directly be loaded and used using unet.pth so that model.py file is not required.  
for example, model=torch.load('./model/unet.pth') then to device.
Please help me with this.... :)

**Comment by manhdung20112000** [comment]
Hi there,
Thanks for raising your issue. In order to use a `pytorch` model, it's necessary to initialized it architecture before loading pre-trained weight or inferring it.

You can find the `UNet` class here [in line 9 located at `model/model.py`](https://github.com/manhdung20112000/speech-enhancement/blob/main/model/model.py#L9)

**Comment by manhdung20112000** [comment]
I will close this issue. If you have any further questions, please raise an issue.
Stay safe.
